#!/bin/bash

tmpfile='./p2000.lst'
url='http://p2000mobiel.nl/'
region='40/geheel-nederland.html'

red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
blue="\e[0;34m"
magenta="\e[0;35m"
redb="\e[1;31m"
greenb="\e[1;32m"
yellowb="\e[1;33m"
blueb="\e[1;34m"
magentab="\e[1;35m"
norm="\e[0m"

# start loop
while true; do
	clear

	# download p2000 alerts for Gelderland-Midden
	wget -O ${tmpfile} -qq ${url}${region}

	# strip all html and realign content
	grep "<div class" ${tmpfile} | egrep -v "date|call_type" | sed -e 's/<[^>]*>//g' -e 's/n\[/n\n\[/g' -e 's/)\[/)\n\[/g' -e 's/d\[/d\n\[/g' -e 's/e\[/e\n\[/g' | head -n 40 > ${tmpfile}.tmp
	mv ${tmpfile}.tmp ${tmpfile}


	diff -Naur ${tmpfile}.old ${tmpfile} | grep ^+ | grep -v ^+++ | sed -e 's/^+//g' > ${tmpfile}.new

	# show new alerts in bold
	while read line; do
        	if [[ $(egrep 'Lifeliner' <<< ${line}) ]]; then
                	echo -e "${greenb}${line}${norm}"
        	elif [[ $(egrep 'GLM_|BRW|Brand|^P\ |[pP][rR][iI][oO]' <<< ${line}) ]]; then
                	echo -e "${redb}${line}${norm}"
        	elif [[ $(egrep 'A[1-2]|[aA][mM][bB][uU]|B[1-2]|CPA|Solo|VWS|Wachtarts|RAVAA|RAV|MKA|RAD|GHOR' <<< ${line}) ]]; then
                	echo -e "${yellowb}${line}${norm}"
        	elif [[ $(egrep 'Kust|KNRM' <<< ${line}) ]]; then
                	echo -e "${magentab}${line}${norm}"
        	else
                	echo -e "${blueb}${line}${norm}"
        	fi
	done < ${tmpfile}.new


# display alerts with color
	while read line; do
		if [[ $(egrep 'Lifeliner' <<< ${line}) ]]; then
                	echo -e "${green}${line}${norm}"
		elif [[ $(egrep 'GLM_|BRW|Brand|^P\ |[pP][rR][iI][oO]' <<< ${line}) ]]; then
                	echo -e "${red}${line}${norm}"
		elif [[ $(egrep 'A[1-2]|[aA][mM][bB][uU]|B[1-2]|CPA|Solo|VWS|Wachtarts|RAVAA|RAV|MKA|RAD|GHOR' <<< ${line}) ]]; then 
			echo -e "${yellow}${line}${norm}"
		elif [[ $(egrep 'Kust|KNRM' <<< ${line}) ]]; then
			echo -e "${orange}${line}${norm}"
		else
			echo -e "${blue}${line}${norm}"
		fi
	done < ${tmpfile}.old

	# cleanup
	mv ${tmpfile} ${tmpfile}.old
	rm ${tmpfile}.new
	
	sleep 60
done
