#!/bin/bash

# p2000-nl: this script will show all p2000 notifications of the Gelderland provance of The Netherlands
#
# author  : harald van der laan
# date    : 2016/06/23
# version : v1.0.1
#
# requirements:
# - internet connection (or via a proxy)
# - curl
#
# changelog:
# v1.0.0	initial version						harald van der laan
# v1.0.1	added proxy support					harald van der laan

if [ -z $(which curl) ]; then
    echo "[-] requirment curl missing."
    exit 1
fi

tmpfile='./p2000.lst'
url='http://p2000mobiel.nl/'
region='40/geheel-nederland.html'

red="\e[38;5;9m"
green="\e[38;5;118m"
yellow="\e[38;5;220m"
blue="\e[38;5;39m"
orange="\e[38;5;208m"
norm="\e[0m"

# download p2000 alerts for Gelderland-Midden
if [ -z ${1} ]; then
    curl -o ${tmpfile} -sL ${url}${region}
else
    curl --proxy ${1} -o ${tmpfile} -sL ${url}${region}
fi

# strip all html and realign content
grep "<div class" ${tmpfile} | egrep -v "date|call_type" | sed -e 's/<[^>]*>//g' -e 's/n\[/n\n\[/g' -e 's/)\[/)\n\[/g' | head -n 40 > ${tmpfile}.tmp
mv ${tmpfile}.tmp ${tmpfile}

# display alerts with color
while read line; do
    if [[ $(egrep 'Lifeliner|LFL|MMT|mmt' <<< ${line}) ]]; then
        echo -e "${green}${line}${norm}"
    elif [[ $(egrep 'GLM_|BRW|Brand|^[Pp][Rr][Ii][Oo]|^[Pp]\ |^AL' <<< ${line}) ]]; then
        echo -e "${red}${line}${norm}"
    elif [[ $(egrep 'Wachtarts' <<< ${line}) ]]; then
        echo -e ${blue}${line}${norm}
    elif [[ $(egrep 'A[1-2]|[Aa][Mm][Bb][Uu]|B[1-2]|Solo|VWS|CPA|SEH|MKA|RAV|RAVAA|GHOR|OvDG' <<< ${line}) ]]; then 
        echo -e "${yellow}${line}${norm}"
    elif [[ $(egrep 'Kust|KNRM|KNBRD' <<< ${line}) ]]; then
        echo -e "${orange}${line}${norm}"
    else
        echo -e "${blue}${line}${norm}"
    fi
done < ${tmpfile}

# cleanup
rm ${tmpfile}
