#!/bin/bash

# p2000: this script will show all p2000 notifications of the Gelderland provance of The Netherlands
#
# author  : harald van der laan
# date    : 2016/06/23
# version : v1.0.1
#
# requirements:
# - internet connection (or via a proxy)
# - curl
#
# changelog:
# v1.0.0        initial version                                         harald van der laan
# v1.0.1        added proxy support                                     harald van der laan

if [ -z $(which curl) ]; then
	echo "[-] requirement curl missing"
	exit 1
fi

tmpfile='./p2000.lst'
url='http://p2000mobiel.nl/'
region='40/geheel-nederland.html'

red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
blue="\e[0;34m"
magenta="\e[0;35m"
redb="\e[1;31m"
greenb="\e[1;32m"
yellowb="\e[1;33m"
blueb="\e[1;34m"
magentab="\e[1;35m"
norm="\e[0m"

# start loop
while true; do
    clear

    # download p2000 alerts for Gelderland-Midden
    if [ -z ${1} ]; then
        curl -o ${tmpfile} -sL ${url}${region}
    else
        curl --proxy ${1} -o ${tmpfile} -sL ${url}${region}
    fi

    # strip all html and realign content
    grep "<div class" ${tmpfile} | egrep -v "date|call_type" | sed -e 's/<[^>]*>//g' -e 's/n\[/n\n\[/g' -e 's/)\[/)\n\[/g' -e 's/d\[/d\n\[/g' -e 's/e\[/e\n\[/g' | head -n 40 > ${tmpfile}.tmp
    mv ${tmpfile}.tmp ${tmpfile}

    if [ ! -f ${tmpfile}.old ]; then
        touch ${tmpfile}.old
    fi
    diff -Naur ${tmpfile}.old ${tmpfile} | grep ^+ | grep -v ^+++ | sed -e 's/^+//g' > ${tmpfile}.new

    # show new alerts in bold
    while read line; do
        if [[ $(egrep 'Lifeliner' <<< ${line}) ]]; then
            echo -e "${greenb}${line}${norm}"
        elif [[ $(egrep 'GLM_|BRW|Brand|^P\ |[pP][rR][iI][oO]' <<< ${line}) ]]; then
            echo -e "${redb}${line}${norm}"
        elif [[ $(egrep 'Wachtwarts' <<< ${line}) ]]; then
            echo -e "${blueb}${line}${norm}"
        elif [[ $(egrep 'A[1-2]|[aA][mM][bB][uU]|B[1-2]|CPA|Solo|VWS|Wachtarts|RAVAA|RAV|MKA|RAD|GHOR|OvDG' <<< ${line}) ]]; then
            echo -e "${yellowb}${line}${norm}"
        elif [[ $(egrep 'Kust|KNRM|KNBRD' <<< ${line}) ]]; then
            echo -e "${magentab}${line}${norm}"
        else
            echo -e "${blueb}${line}${norm}"
        fi
    done < ${tmpfile}.new

    # display alerts with color
    while read line; do
        if [[ $(egrep 'Lifeliner' <<< ${line}) ]]; then
            echo -e "${green}${line}${norm}"
        elif [[ $(egrep 'GLM_|BRW|[Bb]rand|^P\ |[pP][rR][iI][oO]' <<< ${line}) ]]; then
            echo -e "${red}${line}${norm}"
        elif [[ $(egrep 'Wachtarts' <<< ${line}) ]]; then
            echo -e "${blue}${line}${norm}"
        elif [[ $(egrep 'A[1-2]|[aA][mM][bB][uU]|B[1-2]|CPA|Solo|VWS|Wachtarts|RAVAA|RAV|MKA|RAD|GHOR|OvDG' <<< ${line}) ]]; then 
            echo -e "${yellow}${line}${norm}"
        elif [[ $(egrep 'Kust|KNRM|KNBRD' <<< ${line}) ]]; then
            echo -e "${magenta}${line}${norm}"
        else
            echo -e "${blue}${line}${norm}"
        fi
    done < ${tmpfile}.old

    # cleanup
    mv ${tmpfile} ${tmpfile}.old
    rm ${tmpfile}.new
	
    sleep 60
done
